apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-slave
    spec:
      containers:
        - name: master
          image: firasdotcom/mysql-master
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_REPLICATION_USER
              value: 'user'
            - name: MYSQL_REPLICATION_PASSWORD
              value: 'pass'
