apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-worker
  labels:
    name: mysql-worker
spec:
  replicas: 1
  selector:
    name: mysql-worker
  template:
    metadata:
      labels:
        name: mysql-worker
    spec:
      containers:
        - name: worker
          image: firasdotcom/mysql-worker
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_REPLICATION_USER
              value: 'user'
            - name: MYSQL_REPLICATION_PASSWORD
              value: 'pass'
